terraform-2
Otus-DevOps-2021-11/Emix_infra pull request #7
Opened 2022-01-13 21:10 UTC by Emix

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Стеджи и модули

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2022-01-14 13:55 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Стоит свериться с результатами тестов, там ооооочень много красного =(
ДЗ возвращаю на доработку

2022-01-14 18:08 UTC, Emix commented
> Здравствуйте!) Проверил ваше дз Стоит свериться с результатами тестов, там ооооочень много красного =( ДЗ возвращаю на доработку

Исправил, просто не закомитил ☺️

2022-01-16 15:23 UTC, mrgreyves requested changes
Здравствуйте!)
Осталось совсем чуть-чуть, поправить пустые строки =)
Давайте уже дожмем эту домашку =)

2022-01-17 06:10 UTC, Emix commented
> Здравствуйте!) Осталось совсем чуть-чуть, поправить пустые строки =) Давайте уже дожмем эту домашку =)

Поправил, файлики example, вроде все зеленое ☺️

2022-01-17 07:46 UTC, mrgreyves requested changes
Здравствуйте!)
Остался небольшой косячок, оставил комментарий к файлу
Давайте поправим =)

2022-01-17 07:46 UTC, mrgreyves commented on terraform/storage-bucket.tf
> +some = "123"
Вот тут вы явно что-то откуда то случайно вставили =)

2022-01-17 14:21 UTC, Emix commented on terraform/storage-bucket.tf
> +some = "123"
Поправил

2022-01-18 08:37 UTC, mrgreyves approved these changes
Здравствуйте!)
Терраформ мы починили, но пакер сломался =)
Оставлю починку пакера исключительно на вас 
Там не сложно
А основное дз я могу принять =)

2022-01-18 13:30 UTC, merged